version: "3"

services:

  webserver:
    image: nginx:1.13.12-alpine
    volumes:
      - ../build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: ./.env.webserver
    networks:
      - rev-proxy

networks:
  rev-proxy:
    external:
      name: rev-proxy
