FROM node:13.7.0-alpine
RUN addgroup -S app && adduser -S app -G app
WORKDIR /home/app
COPY package.json .
COPY package-lock.json .
RUN ["npm", "install"]
COPY public/ ./public/
COPY src/ ./src/
RUN chmod -R 777 /home/app
USER app
CMD ["npm", "run", "build"]
